### ISSUE TITLE
boolean validator to validate value is always set to either true or false.

### ISSUE THREAD

**Issue by OmkarG1986** [23andMe/Yamale#222]
Boolean validator should have option to validate if set boolean value is either true or false as per the requirement.

e.g. I have one flag based boolean field "create_iac_project". This field is always required to set to true. Withe below boolean validation in schema it doesnt serve the purpose as validation passes even if the filed value is set to boolean false. 

`create_iac_project   : bool(required=True)`

As a WA i tried to use enum validator but enum treats the arguments of type string instead of boolean and i couldnt find anyways to pass type of the argument to enum. 

create_iac_project   : enum('false', ignore_case=True)

> {"ok": false, "errors": {"/rules/example.yaml": ["create_iac_project: 'False' not in ('false',)"

my Data/yaml file that I am validating looks like below:

```
# Flag
create_project       : false                      # Flag for base project creation. Will stop creation of any resources if set to false
create_iac_project   : false                       # Flag for IaC project creation
create_subnet        : false                      # Flag for subnet creation
create_os_patch      : false                       # Flag for OS Patch Manager 
```

**Comment by mechie** [comment]
Have you tried giving enum a Python Boolean? Like so:
```yaml
create_iac_project : enum(False)
```

**Comment by mildebrandt** [comment]
Right, @mechie is correct here. There are two things that were missed when trying to use the `enum` validator:
1. The validator doesn't have an `ignore_case` keyword.
2. A string was used instead of a boolean. 

https://github.com/23andMe/Yamale#enum---enumprimitives

Similarly, the `required` keyword that was used in the `bool` validator indicates that this field is required to be present in the yaml. It doesn't indicate what the value of the field is supposed to be. https://github.com/23andMe/Yamale#validators

Try the following schema:
```yaml
create_iac_project: enum(True)
```

That should get you what you want.

**Comment by OmkarG1986** [comment]
Thank you @mildebrandt @mechie. That was a good catch. I can confirm by using enum(True)/enum(False), Its working as expected. Appreciate your quick response. 

I will mark this issue as closed.
